name: cookiecutter
#base: core18 # the base snap is the execution environment for this snap
version: '1.6.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A command-line utility that creates projects from cookiecutters.
description: |
  A command-line utility that creates projects from cookiecutters (project templates).
  e.g. Python package projects, jQuery plugin projects.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cookiecutter:
    command: env PATH=$SNAP/usr/lib/git-core:$PATH cookiecutter

parts:
  cookiecutter:
    source: https://github.com/audreyr/cookiecutter.git
    source-tag: 1.6.0
    source-type: git
    plugin: python
    stage-packages:
      - libdb5.3
      - git
      - mercurial
